version: '3'

services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    container_name: tisso-bitrix-integration
    restart: unless-stopped
    volumes:
      - ./:/app
